### ISSUE TITLE
Potential attack discussion

### ISSUE THREAD

**Issue by marceljay** [interlay/interlay.github.io#47]
Note: I just looked into the protocol very briefly and would like to understand how the protocol would deal with the following attack.

As the value/peg of the protocol seemingly relies directly on cryptoeconomic security assumptions, even more than renBTC, how would the protocol deal with the a black-thursday-like event affecting **only** the DOT price (or any collateral) but not BTC? 
If the DOT price plunges by let's say 30%, which would lead to many vaults being undercollateralized, the vault owners could simply keep the BTC or use it to buy up DOT before prices move up again.

**Comment by alexeiZamyatin** [comment]
Vaults are liquidated before they drop below the 100% collateralization rate, with a buffer. 
The bigger the buffer (10, 20, 30%) the more secure this is, since users have more time to exit into a stable after they get DOT from the liquidation (before it drops below the 100% of the lost BTC value).
